spring.application.name=Exam01
spring.datasource.url=jdbc:mysql://localhost:3307/sesion09TSU?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
cloudinary_name=dsite7hnf
cloudinary_api_key=474766147727529
cloudinary_api_secret_key=6JKDOCiv9m1UmRSPL9lFyadtDcw
